public class ApprovalRequestConstants {

    public static final String RESOLUTION_PENDING = 'Pendiente';
    public static final String RESOLUTION_APPROVED = 'Aprobado';
    public static final String RESOLUTION_REJECTED = 'Rechazado';

    public static final String STATUS_COMPLETED = 'Completado';
    public static final String STATUS_DISMISSED = 'Desestimado';
    public static final String STATUS_REVIEWING = 'En revisión';
    public static final String STATUS_PENDING = 'Pendiente otros revisores';
}