public class CPQ_ProductFamilies {
    
    public static final String NONE             = 'None';
    public static final String DEPOSITOS        = 'Depósitos';
    public static final String TRANSPORTE       = 'Transporte';
    public static final String LEGALIZACIONES   = 'Legalizaciones';
    public static final String INSTALACIONES    = 'Instalaciones';
    public static final String PROYECTO_MEMORIA = 'Proyecto/Memoria';
    public static final String OBRA_CIVIL       = 'Obra civil';
    public static final String VALLADO          = 'Vallado';
    public static final String OTROS_EQUIPOS    = 'Otros Equipos';
    public static final String PRIMASERVICIOS   = 'Primaservicios';
    public static final String INVERSION        = 'Inversión';
    public static final String ALQUILER         = 'Alquiler';
    public static final String DESCUENTOS       = 'Descuentos';
    public static final String TARIFAS          = 'Tarifas';
}